package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private String docNo;
     private String docLastname;
     private String docFirstname;
     private String streetName;
     private String houseNumber;
     private String city;
     private String cellphone;
     private Date dateOfBirth;
     private String sex;
     private Double currentSalary;
     private Set patients = new HashSet(0);

    public Doctor() {
    }

	
    public Doctor(String docNo) {
        this.docNo = docNo;
    }
    public Doctor(String docNo, String docLastname, String docFirstname, String streetName, String houseNumber, String city, String cellphone, Date dateOfBirth, String sex, Double currentSalary, Set patients) {
       this.docNo = docNo;
       this.docLastname = docLastname;
       this.docFirstname = docFirstname;
       this.streetName = streetName;
       this.houseNumber = houseNumber;
       this.city = city;
       this.cellphone = cellphone;
       this.dateOfBirth = dateOfBirth;
       this.sex = sex;
       this.currentSalary = currentSalary;
       this.patients = patients;
    }
   
    public String getDocNo() {
        return this.docNo;
    }
    
    public void setDocNo(String docNo) {
        this.docNo = docNo;
    }
    public String getDocLastname() {
        return this.docLastname;
    }
    
    public void setDocLastname(String docLastname) {
        this.docLastname = docLastname;
    }
    public String getDocFirstname() {
        return this.docFirstname;
    }
    
    public void setDocFirstname(String docFirstname) {
        this.docFirstname = docFirstname;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public String getHouseNumber() {
        return this.houseNumber;
    }
    
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Double getCurrentSalary() {
        return this.currentSalary;
    }
    
    public void setCurrentSalary(Double currentSalary) {
        this.currentSalary = currentSalary;
    }
    public Set getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set patients) {
        this.patients = patients;
    }




}


