package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nurse generated by hbm2java
 */
public class Nurse  implements java.io.Serializable {


     private String nurseId;
     private String firstName;
     private String lastName;
     private String streetName;
     private Integer houseNo;
     private String city;
     private Integer cellphone;
     private Date dateOfBirth;
     private Character sex;
     private Set patients = new HashSet(0);
     private Set rooms = new HashSet(0);

    public Nurse() {
    }

	
    public Nurse(String nurseId) {
        this.nurseId = nurseId;
    }
    public Nurse(String nurseId, String firstName, String lastName, String streetName, Integer houseNo, String city, Integer cellphone, Date dateOfBirth, Character sex, Set patients, Set rooms) {
       this.nurseId = nurseId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.streetName = streetName;
       this.houseNo = houseNo;
       this.city = city;
       this.cellphone = cellphone;
       this.dateOfBirth = dateOfBirth;
       this.sex = sex;
       this.patients = patients;
       this.rooms = rooms;
    }
   
    public String getNurseId() {
        return this.nurseId;
    }
    
    public void setNurseId(String nurseId) {
        this.nurseId = nurseId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public Integer getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(Integer houseNo) {
        this.houseNo = houseNo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(Integer cellphone) {
        this.cellphone = cellphone;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public Set getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set patients) {
        this.patients = patients;
    }
    public Set getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set rooms) {
        this.rooms = rooms;
    }




}


