package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1



/**
 * PatientAppointmentId generated by hbm2java
 */
public class PatientAppointmentId  implements java.io.Serializable {


     private int appNo;
     private String receptionistRecepNo;

    public PatientAppointmentId() {
    }

    public PatientAppointmentId(int appNo, String receptionistRecepNo) {
       this.appNo = appNo;
       this.receptionistRecepNo = receptionistRecepNo;
    }
   
    public int getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(int appNo) {
        this.appNo = appNo;
    }
    public String getReceptionistRecepNo() {
        return this.receptionistRecepNo;
    }
    
    public void setReceptionistRecepNo(String receptionistRecepNo) {
        this.receptionistRecepNo = receptionistRecepNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientAppointmentId) ) return false;
		 PatientAppointmentId castOther = ( PatientAppointmentId ) other; 
         
		 return (this.getAppNo()==castOther.getAppNo())
 && ( (this.getReceptionistRecepNo()==castOther.getReceptionistRecepNo()) || ( this.getReceptionistRecepNo()!=null && castOther.getReceptionistRecepNo()!=null && this.getReceptionistRecepNo().equals(castOther.getReceptionistRecepNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAppNo();
         result = 37 * result + ( getReceptionistRecepNo() == null ? 0 : this.getReceptionistRecepNo().hashCode() );
         return result;
   }   


}


