package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientAppointment generated by hbm2java
 */
public class PatientAppointment  implements java.io.Serializable {


     private PatientAppointmentId id;
     private Receptionist receptionist;
     private Date appDate;
     private Date appTime;

    public PatientAppointment() {
    }

	
    public PatientAppointment(PatientAppointmentId id, Receptionist receptionist) {
        this.id = id;
        this.receptionist = receptionist;
    }
    public PatientAppointment(PatientAppointmentId id, Receptionist receptionist, Date appDate, Date appTime) {
       this.id = id;
       this.receptionist = receptionist;
       this.appDate = appDate;
       this.appTime = appTime;
    }
   
    public PatientAppointmentId getId() {
        return this.id;
    }
    
    public void setId(PatientAppointmentId id) {
        this.id = id;
    }
    public Receptionist getReceptionist() {
        return this.receptionist;
    }
    
    public void setReceptionist(Receptionist receptionist) {
        this.receptionist = receptionist;
    }
    public Date getAppDate() {
        return this.appDate;
    }
    
    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }
    public Date getAppTime() {
        return this.appTime;
    }
    
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }




}


