package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private PatientId id;
     private Doctor doctor;
     private Nurse nurse;
     private PatientMedication patientMedication;
     private Receptionist receptionist;
     private String patientFirstName;
     private String patientLastName;
     private String streetName;
     private Integer houseNo;
     private String city;
     private Integer cellphone;
     private Date dateOfBirth;
     private Character sex;
     private Character maritalStatus;
     private Date dateRegistration;
     private String admissionStatus;

    public Patient() {
    }

	
    public Patient(PatientId id, Doctor doctor, Nurse nurse, PatientMedication patientMedication, Receptionist receptionist) {
        this.id = id;
        this.doctor = doctor;
        this.nurse = nurse;
        this.patientMedication = patientMedication;
        this.receptionist = receptionist;
    }
    public Patient(PatientId id, Doctor doctor, Nurse nurse, PatientMedication patientMedication, Receptionist receptionist, String patientFirstName, String patientLastName, String streetName, Integer houseNo, String city, Integer cellphone, Date dateOfBirth, Character sex, Character maritalStatus, Date dateRegistration, String admissionStatus) {
       this.id = id;
       this.doctor = doctor;
       this.nurse = nurse;
       this.patientMedication = patientMedication;
       this.receptionist = receptionist;
       this.patientFirstName = patientFirstName;
       this.patientLastName = patientLastName;
       this.streetName = streetName;
       this.houseNo = houseNo;
       this.city = city;
       this.cellphone = cellphone;
       this.dateOfBirth = dateOfBirth;
       this.sex = sex;
       this.maritalStatus = maritalStatus;
       this.dateRegistration = dateRegistration;
       this.admissionStatus = admissionStatus;
    }
   
    public PatientId getId() {
        return this.id;
    }
    
    public void setId(PatientId id) {
        this.id = id;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Nurse getNurse() {
        return this.nurse;
    }
    
    public void setNurse(Nurse nurse) {
        this.nurse = nurse;
    }
    public PatientMedication getPatientMedication() {
        return this.patientMedication;
    }
    
    public void setPatientMedication(PatientMedication patientMedication) {
        this.patientMedication = patientMedication;
    }
    public Receptionist getReceptionist() {
        return this.receptionist;
    }
    
    public void setReceptionist(Receptionist receptionist) {
        this.receptionist = receptionist;
    }
    public String getPatientFirstName() {
        return this.patientFirstName;
    }
    
    public void setPatientFirstName(String patientFirstName) {
        this.patientFirstName = patientFirstName;
    }
    public String getPatientLastName() {
        return this.patientLastName;
    }
    
    public void setPatientLastName(String patientLastName) {
        this.patientLastName = patientLastName;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public Integer getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(Integer houseNo) {
        this.houseNo = houseNo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(Integer cellphone) {
        this.cellphone = cellphone;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public Character getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(Character maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public Date getDateRegistration() {
        return this.dateRegistration;
    }
    
    public void setDateRegistration(Date dateRegistration) {
        this.dateRegistration = dateRegistration;
    }
    public String getAdmissionStatus() {
        return this.admissionStatus;
    }
    
    public void setAdmissionStatus(String admissionStatus) {
        this.admissionStatus = admissionStatus;
    }




}


