package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Receptionist generated by hbm2java
 */
public class Receptionist  implements java.io.Serializable {


     private String recepNo;
     private String firstName;
     private String lastName;
     private String streetName;
     private Integer houseNo;
     private String city;
     private Integer cellphoneNo;
     private String username;
     private Set patients = new HashSet(0);
     private Set patientAppointments = new HashSet(0);

    public Receptionist() {
    }

	
    public Receptionist(String recepNo) {
        this.recepNo = recepNo;
    }
    public Receptionist(String recepNo, String firstName, String lastName, String streetName, Integer houseNo, String city, Integer cellphoneNo, String username, Set patients, Set patientAppointments) {
       this.recepNo = recepNo;
       this.firstName = firstName;
       this.lastName = lastName;
       this.streetName = streetName;
       this.houseNo = houseNo;
       this.city = city;
       this.cellphoneNo = cellphoneNo;
       this.username = username;
       this.patients = patients;
       this.patientAppointments = patientAppointments;
    }
   
    public String getRecepNo() {
        return this.recepNo;
    }
    
    public void setRecepNo(String recepNo) {
        this.recepNo = recepNo;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public Integer getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(Integer houseNo) {
        this.houseNo = houseNo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getCellphoneNo() {
        return this.cellphoneNo;
    }
    
    public void setCellphoneNo(Integer cellphoneNo) {
        this.cellphoneNo = cellphoneNo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set patients) {
        this.patients = patients;
    }
    public Set getPatientAppointments() {
        return this.patientAppointments;
    }
    
    public void setPatientAppointments(Set patientAppointments) {
        this.patientAppointments = patientAppointments;
    }




}


