package Hospital;
// Generated Jul 6, 2016 9:46:59 PM by Hibernate Tools 4.3.1



/**
 * RoomId generated by hbm2java
 */
public class RoomId  implements java.io.Serializable {


     private String roomNo;
     private String nurseNurseId;

    public RoomId() {
    }

    public RoomId(String roomNo, String nurseNurseId) {
       this.roomNo = roomNo;
       this.nurseNurseId = nurseNurseId;
    }
   
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getNurseNurseId() {
        return this.nurseNurseId;
    }
    
    public void setNurseNurseId(String nurseNurseId) {
        this.nurseNurseId = nurseNurseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RoomId) ) return false;
		 RoomId castOther = ( RoomId ) other; 
         
		 return ( (this.getRoomNo()==castOther.getRoomNo()) || ( this.getRoomNo()!=null && castOther.getRoomNo()!=null && this.getRoomNo().equals(castOther.getRoomNo()) ) )
 && ( (this.getNurseNurseId()==castOther.getNurseNurseId()) || ( this.getNurseNurseId()!=null && castOther.getNurseNurseId()!=null && this.getNurseNurseId().equals(castOther.getNurseNurseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRoomNo() == null ? 0 : this.getRoomNo().hashCode() );
         result = 37 * result + ( getNurseNurseId() == null ? 0 : this.getNurseNurseId().hashCode() );
         return result;
   }   


}


